# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Clientui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(777, 440)
        MainWindow.setMinimumSize(QtCore.QSize(777, 440))
        MainWindow.setMaximumSize(QtCore.QSize(777, 440))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(20, 350, 601, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(20, 20, 601, 321))
        self.textEdit.setObjectName("textEdit")
        self.labelConnectionInfo = QtWidgets.QLabel(self.centralwidget)
        self.labelConnectionInfo.setGeometry(QtCore.QRect(20, 382, 131, 21))
        self.labelConnectionInfo.setObjectName("labelConnectionInfo")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(630, 20, 130, 321))
        self.listWidget.setObjectName("listWidget")
        self.pushButtonSend = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonSend.setGeometry(QtCore.QRect(630, 350, 131, 31))
        self.pushButtonSend.setObjectName("pushButtonSend")
        self.labelNickname = QtWidgets.QLabel(self.centralwidget)
        self.labelNickname.setGeometry(QtCore.QRect(20, 0, 271, 21))
        self.labelNickname.setText("")
        self.labelNickname.setObjectName("labelNickname")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 777, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuConnection = QtWidgets.QMenu(self.menubar)
        self.menuConnection.setObjectName("menuConnection")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionConnect_to_Chat = QtWidgets.QAction(MainWindow)
        self.actionConnect_to_Chat.setObjectName("actionConnect_to_Chat")
        self.actionDisconnect = QtWidgets.QAction(MainWindow)
        self.actionDisconnect.setObjectName("actionDisconnect")
        self.menuFile.addAction(self.actionExit)
        self.menuConnection.addAction(self.actionConnect_to_Chat)
        self.menuConnection.addAction(self.actionDisconnect)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuConnection.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelConnectionInfo.setText(_translate("MainWindow", "Waiting for connection..."))
        self.pushButtonSend.setText(_translate("MainWindow", "SEND"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuConnection.setTitle(_translate("MainWindow", "Connection"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionConnect_to_Chat.setText(_translate("MainWindow", "Connect to Chat !"))
        self.actionDisconnect.setText(_translate("MainWindow", "Disconnect !"))
